# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    tags:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Odin
        # Use the setup-odin action to install the compiler
        uses: laytan/setup-odin@v2
        with:
          # The GITHUB_TOKEN secret is automatically set in an action
          token: ${{ secrets.GITHUB_TOKEN }}
          # Optional: specify a version, e.g., 'latest', 'nightly', or a specific release
          release: 'latest' 
      - name: Verify Odin installation
        # The 'odin' command is now available in the PATH
        run: odin version
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
          --repo="$GITHUB_REPOSITORY" \
          --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
          --generate-notes
      - name: Build Odin project
        # Replace 'src/main.odin' with the entry point of your application
        run: odin build .
      - name: Display Directory
        run: ls
      - name: Package Game
        run: |
          mkdir soccer_man/
          cp -r ./assets/ soccer_man/assets/
          cp kickman.exe soccer_man/soccer_man.exe
          Compress-Archive -Path ./soccer_man/* -Destination ./soccer_man.zip
      - name: Upload release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./soccer_man.zip
