# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Odin
        # Use the setup-odin action to install the compiler
        uses: laytan/setup-odin@v2
        with:
          # The GITHUB_TOKEN secret is automatically set in an action
          token: ${{ secrets.GITHUB_TOKEN }}
          # Optional: specify a version, e.g., 'latest', 'nightly', or a specific release
          release: 'latest' 

      - name: Verify Odin installation
        # The 'odin' command is now available in the PATH
        run: odin version

      - name: Build Odin project
        # Replace 'src/main.odin' with the entry point of your application
        run: odin build .
      - name: Display Directory
        run: ls
      - name: Upload build artifact
        uses: actions/upload-artifact@v4 # Use the recommended v4 action
        with:
          name: kickman.exe
          path: dist/kickman.exe # The path to the files to upload
